# -*- coding: utf-8 -*-
# Generated by Django 3.1.1 on 2020-09-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app05_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='标签名称', max_length=50),
        ),
    ]
