# -*- coding: utf-8 -*-
# Generated by Django 3.1 on 2020-09-11 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TalkGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=20, verbose_name='组名')),
                ('brief', models.CharField(blank=True, default='管理层很懒，不想写简介...', max_length=255, null=True, verbose_name='简介')),
                ('admins', models.ManyToManyField(blank=True, related_name='group_admin', to=settings.AUTH_USER_MODEL, verbose_name='管理员')),
                ('members', models.ManyToManyField(blank=True, related_name='group_member', to=settings.AUTH_USER_MODEL, verbose_name='群员')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_owner', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '聊天组',
                'verbose_name_plural': '聊天组',
            },
        ),
    ]
