repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v3.2.0
    hooks:
    -   id: check-docstring-first
    -   id: debug-statements
-   repo: https://github.com/PyCQA/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        args:
            - --max-line-length=120
        exclude: ^conf/(docker|redis-docker)/,^day01/settings/
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.7.2
    hooks:
    -   id: pyupgrade
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.4
    hooks:
    -   id: autopep8
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.8.1
    hooks:
    -   id: eslint
        files: \.[jt]sx?$
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.6.0
    hooks:
    -   id: pylint
        exclude: ^day01/settings/, ^conf/(docker|redis-docker)/
        files:
            settings.py, base.py
-   repo: https://github.com/pycqa/isort
    rev: 5.3.0
    hooks:
      - id: isort