# Generated by Django 3.1 on 2020-08-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='xxx', max_length=20, null=True)),
                ('info', models.CharField(blank=True, default='xxx', max_length=20, null=True)),
            ],
        ),
    ]
