# Generated by Django 3.1 on 2020-09-03 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app04', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
